### ISSUE TITLE
Tagged checkouts use master for exporters (and thus cause build failures)

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#329]
# Workaround

If your [exporter build is faililng](https://github.com/konveyor/pelorus/issues/303), change your exporter's `source_ref` to the same tag you have checked out.

You can also check out the [v1.4.0 Release Candidate](https://github.com/konveyor/pelorus/releases/tag/v1.4.0-rc) and be sure to follow the upgrade instructions in the link.

Alternatively, check out master and use that, but be warned that it is not necessarily stable.

# Root Cause

#286 used features of Python that required Python 3.9 or higher. The Python image was set to 3.9 in #290.

However, there was an edge case we failed to consider: each stable release still points each exporter at `master`. This meant you could have helm charts that said to use an older version of Python to build the image, while using the latest code for it.

# This Issue

This issue will remain open until [v1.4.0](https://github.com/konveyor/pelorus/milestone/3) is released, so that users affected by this can see its status and the workaround.

# Related Issues

- #313 
- #303 

# Remaining Work

- [x] https://github.com/konveyor/pelorus/pull/316
- [x] https://github.com/konveyor/pelorus/pull/320
- [x] https://github.com/konveyor/pelorus/pull/326

**Comment by KevinMGranger** [comment]
Fixed in 1.4.0.
